copyright: ""
site_author: asynx.dev Team
# site_description: asynx.dev !! Not used to use custom meta description code.
copyright: "Copyright &copy; 2020 asynx.dev Team<br/>License: <a href='https://creativecommons.org/licenses/by/4.0/'>CC BY 4.0</a>"
site_name: asynx.dev
site_url: http://localhost:8000/
repo_url: https://github.com/asynx-dev/www
edit_uri: ""
use_directory_urls: false

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true


plugins:
  - bibtex:
      bib_file: "ref/refs.bib"
      cite_style: "pandoc"
  - git-authors:
      show_contribution: true
      show_line_count: false
      count_empty_lines: false
  - git-revision-date
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_page_markdown: "hooks.onpagemarkdown:onpagemarkdown"



theme:
  name: material
  language: en
  palette:
    scheme: preference
    primary: indigo
    accent: deep orange
  font:
    text: Open Sans
    code: Source Code Pro
  favicon: img/favicon.ico
  logo: img/asynx_logo_icon_white.png
  custom_dir: material-theme-overrides

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/asynx-dev/
      name: Our Github Page
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/asynxdev
      name: Our Twitter Profile

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Projects: project/index.md
  - About Us: about.md
  - Contact: contact.md
  - Miscellaneous: misc/index.md
  - '[TR]':
    - Ana Sayfa: index-tr.md
    - Projeler: project/index-tr.md
    - Hakkımızda: about-tr.md
    - İletişim: contact-tr.md
