copyright: ""
site_author: asynx.dev
# site_description: asynx.dev !! Not used to use custom meta description code.
site_name: asynx.dev
site_url: http://localhost:8000/
repo_url: https://github.com/asynx-dev/www
edit_uri: ""

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true


plugins:
  - bibtex:
      bib_file: "ref/refs.bib"
      cite_style: "pandoc"
  - git-authors:
      show_contribution: true
      show_line_count: false
      count_empty_lines: false
  - git-revision-date
  - search


theme:
  name: material
  language: en
  palette:
    scheme: preference
    primary: indigo
    accent: deep orange
  font:
    text: Open Sans
    code: Source Code Pro
  favicon: img/favicon.ico
  logo: img/asynx_icon.png
  custom_dir: material-theme-overrides

nav:
  - Home: index.md
  - Misc.: misc/index.md
