name: markdown-linter
on:
  push:
    branches:
      # All branches
      - '**'
  pull_request:
    branches:
      - main
jobs:
  check-all-md-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g markdownlint-cli
      - run: markdownlint docs
      - run: markdownlint ./
