name: merge-test

on:
  pull_request:
    branches:
      - master

jobs:

  merge-markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install markdownlint-cli
      run: |
        npm install -g markdownlint-cli
    - name: Lint markdown files
      run: |
        markdownlint ./ --ignore ./vendor

  merge-jekyll-build:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
    strategy:
      matrix:
        python-version: ['3.6']
        ruby-version: ['2.7']
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install pipenv
      run: |
        python -m pip install pipenv
    - name: Install Ruby dependencies
      run: |
        bundle update
    - name: Install Python dependencies
      run: |
        pipenv update
    - name: Build the site
      run: |
        bundle exec jekyll build --config _config.yml,_config-deploy.yml,_config-merge.yml
    - name: Test (HTMLProofer)
      run: |
        bundle exec htmlproofer ./_site --disable-external --allow-hash-href --alt-ignore /.*/
    - name: Test (pytest)
      run: |
        pipenv run python test.py pytest
