name: quick-check

on:
  push:
    branches-ignore:
      - master

jobs:

  quick-check-markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install markdownlint-cli
      run: |
        npm install -g markdownlint-cli
    - name: Lint root directory
      run: |
        markdownlint ./
    - name: Lint docs directory
      run: |
        markdownlint src

