name: quick-check

on:
  push:
    branches:
      - !master

jobs:

  quick-check-markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install markdownlint-cli
      run: |
        npm install -g markdownlint-cli
    - name: Lint root directory
      run: |
        markdownlint ./
    - name: Lint docs directory
      run: |
        markdownlint docs

  quick-check-mkdocs-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install pipenv
      run: |
        python -m pip install pipenv
    - name: Install mkdocs and build the site
      run: |
        ./build.py
