name: quick-check

on:
  push:
    branches-ignore:
      - master

jobs:

  quick-check-markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.2.0
    - name: Install markdownlint-cli
      run: |
        npm install
    - name: Lint markdown files
      run: |
        npx -c 'markdownlint ./ --ignore ./vendor --ignore ./node_modules'

